services:
  api-gateway:
    image: faketri33/eshop/backend/api-gateway
    container_name: eshop-backend-api-gateway-service
    labels:
      group: backend
    build:
      context: ../../../api-gateway/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: "../../../env/docker.env"
    volumes:
      - ../../../logs/gateway-service:/app/logs/gateway-service
    profiles:
      - backend
    networks:
      - eshop-network

  analytics-service:
    image: faketri33/eshop/backend/analytics-service
    container_name: eshop-backend-analytics-service
    labels:
      group: backend
    build:
      context: ../../../common/analytics-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    volumes:
      - ../../../logs/analytics-service:/app/logs/analytics-service
    depends_on:
      - kafka
      - redis
    env_file: "../../../env/docker.env"
    profiles:
      - backend
    networks:
      - eshop-network

  discovery-service:
    image: faketri33/eshop/backend/discovery-service
    container_name: eshop-backend-discovery-service
    labels:
      group: backend
    build:
      context: ../../../common/discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    env_file: "../../../env/docker.env"
    profiles:
      - backend
    networks:
      - eshop-network

  catalog-service:
    image: faketri33/eshop/backend/catalog-service
    container_name: eshop-backend-catalog-service
    labels:
      group: backend
    build:
      context: ../../../core/catalog-service
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - ../../../logs/catalog-service:/app/logs/catalog-service
    depends_on:
      - redis
      - elasticsearch
      - kafka
    env_file: "../../../env/docker.env"
    profiles:
      - backend
    networks:
      - eshop-network

  profile-service:
    image: faketri33/eshop/backend/profile-service
    container_name: eshop-backend-profile-service
    labels:
      group: backend
    build:
      context: ../../../core/profile-service
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    volumes:
      - ../../../logs/profile-service:/app/logs/profile-service
    depends_on:
      - services_postgres
    env_file: "../../../env/docker.env"
    profiles:
      - backend
    networks:
      - eshop-network

  cart-service:
    image: faketri33/eshop/backend/cart-service
    container_name: eshop-backend-cart-service
    labels:
      group: backend
    build:
      context: ../../../core/cart-service
      dockerfile: Dockerfile
    ports:
      - "8400:8400"
    volumes:
      - ../../../logs/basket-service:/app/logs/basket-service
    depends_on:
      - services_postgres
    env_file: "../../../env/docker.env"
    profiles:
      - backend
    networks:
      - eshop-network