services:
  postgres:
    image: postgres:15-alpine
    container_name: basket-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5452:5432"
    volumes:
      - basket-postgres-data:/var/lib/postgresql/data

volumes:
  basket-postgres-data:
    driver: local