server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: services
    static_configs:
      - targets: ['localhost']
        labels:
          job: spring-boot
          __path__: /var/log/services/*/service.log

    relabel_configs:
      - source_labels: [__path__]
        regex: .*/var/log/services/([^/]+)-service/service.log
        target_label: service
        replacement: $1

    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: '["@timestamp"]'
            message: message
            service: service
      - labels:
          level:
          service:
      - timestamp:
          source: ts
          format: RFC3339Nano
