services:
  postgres:
    container_name: product_service_postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "catalog"
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5442:5432"